CREATE TABLE TestBankTopics (
    ID UNIQUEIDENTIFIER NOT NULL,
    UserID UNIQUEIDENTIFIER NOT NULL,
    TopicName NVARCHAR(1000) NOT NULL,
    Categories NVARCHAR(4000) NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE TestBankQuestions (
    ID UNIQUEIDENTIFIER NOT NULL,
    TopicID UNIQUEIDENTIFIER NOT NULL,
    QuestionText NVARCHAR(MAX) NOT NULL,
    ImageID UNIQUEIDENTIFIER NULL,
    Difficulty INT NULL,
    Categories NVARCHAR(4000) NULL,
    OrderNumber INT NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE TestBankImages (
    ID UNIQUEIDENTIFIER NOT NULL,
    TopicID UNIQUEIDENTIFIER NOT NULL,
    ImageName NVARCHAR(1000) NOT NULL,
    BlobPath NVARCHAR(1000) NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE TestBankQuestionOptions (
    ID UNIQUEIDENTIFIER NOT NULL,
    QuestionID UNIQUEIDENTIFIER NOT NULL,
    AnswerText NVARCHAR(1000) NOT NULL,
    CorrectAnswer BIT NOT NULL,
    OrderNumber INT NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE TestBankExams (
    ID UNIQUEIDENTIFIER NOT NULL,
    UserID UNIQUEIDENTIFIER NOT NULL,
    TestName NVARCHAR(1000) NOT NULL,
    CreatedTimeStamp DATETIME NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE TestBankExamData (
    ID UNIQUEIDENTIFIER NOT NULL,
    ExamID UNIQUEIDENTIFIER NOT NULL,
    ExamData NVARCHAR(MAX) NOT NULL,
    KeyMode BIT NOT NULL,
    PRIMARY KEY (ID)
);
CREATE TABLE TestBankExamQuestions (
    ID UNIQUEIDENTIFIER NOT NULL,
    ExamID UNIQUEIDENTIFIER NOT NULL,
    QuestionID UNIQUEIDENTIFIER NOT NULL,
    OrderNumber INT NOT NULL,
    PRIMARY KEY (ID)
);


